platform: Any CPU

configuration: Release

before_build:
- cmd: nuget restore "src\Signhost API Client.sln"

build_script: msbuild /m "src\Signhost API Client.sln" /p:Configuration=Release /p:Platform="AnyCPU"